alias rm='/bin/rm -i'

alias rb='mce_cmd -qx rb'
alias wb='mce_cmd -qx wb'
alias rs='mce_cmd -qx rs'
alias wra='mce_cmd -qx wra'
alias rra='mce_cmd -qx rra'
alias wel='mce_cmd -qx wel'
alias rel='mce_cmd -qx rel'
alias mce_reset='mce_cmd -qx mce_reset'
alias dsp_reset='mce_cmd -qx dsp_reset'
