#!/bin/bash

source ~mce/mas_env.bash
source $MAS_SCRIPT/mas_library.bash

AUTO_LOG=$MAS_DATA/auto_log.txt
LOGGER="tee -a $AUTO_LOG"

SCRNAME="auto_acquire"
ERRPREF="ERROR : $SCRNAME :"

#SCRIPTS=`cat /home/mce/mce_config/mce_usrscriptdir.cfg`

start_time=`date`
start_ctime=`print_ctime`

echo "START : $SCRNAME : $start_time" | $LOGGER
echo "ARGS  : $SCRNAME : $@" | $LOGGER

#Process arguments

if [ "$#" != "2" ]; then
    echo "Usage:     auto_acquire <filename> <n_frames>"
    echo $ERRPREF "wrong number of arguments" | $LOGGER
    exit 1
fi

acq_name=$1
n_frames=$2

# args are file_prefix, frame count, card (1,2,3,4,s)
ACQ="mce_run $acq_name $n_frames s"
ACQ_TARGET=0

# Try to start in good health
#health_clear
#if [ "$?" != "0" ]; then
#    echo $ERRPREF "health_clear failed!  Check MCE/DAS." | $LOGGER
#    exit 1
#fi

# Do a check to be sure
#check_one_behind && check_reset && check_extra_words
#if [ "$?" != "0" ]; then
#    echo $ERRPREF "health check failed!  Check MCE/DAS." | $LOGGER
#    exit 1
#fi


# Start acquisition
$ACQ
if [ "$?" != "$ACQ_TARGET" ]; then
    echo $ERRPREF "'$ACQ' returned error!" | $LOGGER
    exit 1
fi

# Check health, for the record
#check_extra_words
#if [ "$?" != "0" ]; then
#   echo $ERRPREF "check_extra_words returned positive" | $LOGGER
#fi
#check_one_behind
#if [ "$?" != "0" ]; then
#   echo $ERRPREF "check_one_behind returned positive" | $LOGGER
#fi
#check_reset
#if [ "$?" != "0" ]; then
#   echo $ERRPREF "check_reset returned positive" | $LOGGER
#fi

# Check for CC losing lock with sync box
#clk=`command_reply rb cc select_clk`
#if [ "$clk" != "00000001" ]; then
#   echo $ERRPREF "select_clk is now $clk" | $LOGGER
#fi

# Record keeping: PCI diagnostic and time elapsed

diag=`print_dsp_diagnostic`
echo "INFO  : $SCRNAME : $diag" | $LOGGER
delta_ctime=`print_elapsed $start_ctime`
echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
echo
