#!/usr/bin/python

import auto_setup as ast

from optparse import OptionParser

o = OptionParser()
o.add_option('--rc', action='append', default=[])
o.add_option('-i', '--interactive', action='store_true')
o.add_option('-s', '--shortness', default=0, type='int')
o.add_option('--first-stage', default=None)
o.add_option('--last-stage', default=None)
o.add_option('--no-check-bias', default=None)
o.add_option('--reg-note', default=None)
opts, args = o.parse_args()

# Process...
if opts.interactive:
    ast.util.interactive_errors()
# opts.rc should be integers or 's' for all.
opts.rc = [x.lower() for x in opts.rc]
if (len(opts.rc) == 0) or ('s' in opts.rc):
    opts.rc = None
else:
    opts.rc = [int(x) for x in opts.rc]

if (opts.no_check_bias):
    check_bias=False
else:
    check_bias=True

# Tune.
ast.auto_setup(rcs=opts.rc, short=opts.shortness, reg_note=opts.reg_note,
               first_stage=opts.first_stage, last_stage=opts.last_stage,
               check_bias=check_bias)
