#!/bin/bash

# initialise environment
eval `${MAS_CONFIG:-/usr/mce/bin/mas_config} -s`

source $MAS_SCRIPT/mas_library.bash

AUTO_LOG=$MAS_DATA/auto_log.txt
LOGGER="tee -a $AUTO_LOG"
SCRNAME=auto_stop

start_time=`date`
start_ctime=`print_ctime`

echo "START : $SCRNAME : $start_time" | $LOGGER

echo Resetting MCE
mce_cmd -qx mce_reset
sleep 2
echo Resetting PCI card
mce_cmd -qx dsp_reset
sleep 1
echo Issuing fakestop for acq programs
mce_cmd -qx fakestop
sleep 1
echo Emptying buffer in case there were no acq programs...
mce_cmd -qx empty
sleep 1
echo Reconfiguring MCE
mce_reconfig
sleep 1

delta_ctime=`print_elapsed $start_ctime`
echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
