#!/bin/bash

# initialise environment
eval `${MAS_CONFIG:-/usr/mce/bin/mas_config} -s`

source $MAS_SCRIPT/mas_library.bash

short="$1"
note="$3"

if [ "$1" = "" ]; then
    short="0"
fi

RC=",rcs=[$2]"

if [ "$2" == "" ] || [ "$2" == "s" ] || [ "$2" == "S" ] || [ "$2" == "all" ]; then
    RC=""
fi

AUTO_LOG=$MAS_DATA/auto_log.txt
LOGGER="tee -a $AUTO_LOG"

SCRNAME="auto_setup_squids_sh"
ERRPREF="ERROR : $SCRNAME :"

SCRIPTS=$MAS_SCRIPT
IDL_PRO=$MAS_IDL

SETUP_TARGET=99 #return value that indicates completion
#SETUP_IDL="auto_setup_squids,short=$short,/check_bias $RC"
SETUP_IDL="auto_setup_squids,short=$short $RC"

start_time=`date`
ctime=`print_ctime`

echo "START : $SCRNAME : $start_time" | $LOGGER
echo "INFO  : $SCRNAME : ctime=$ctime" | $LOGGER
echo "ARGS  : $SCRNAME : $@" | $LOGGER

# Set observer log variable
export MAS_LOGID="$note"

# Start auto_setup

cd $IDL_PRO
idl -quiet <<EOF	
${SETUP_IDL}
EOF

err=$?
if [ "$err" != "$SETUP_TARGET" ]; then
    echo $ERRPREF "'$SETUP_IDL' returned error! [$err]" | $LOGGER
    exit 1
fi

err=$?
if [ "$err" != "0" ]; then
   echo $ERRPREF "Archiving to $ZIP_DEST failed [$err]" | $LOGGER
   exit 1
fi

delta_ctime=`print_elapsed $ctime`
echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
