#!/bin/bash

## source /home/mce/mas_env.bash
source $MAS_SCRIPT/mas_library.bash

AUTO_LOG=$MAS_DATA/auto_log.txt
LOGGER="tee -a $AUTO_LOG"

SCRNAME="auto_bias_step"
ERRPREF="ERROR : $SCRNAME :"

start_time=`date`
start_ctime=`print_ctime`

echo "START : $SCRNAME : $start_time" | $LOGGER
echo "ARGS  : $SCRNAME : $@" | $LOGGER

#Process arguments

if [ "$#" != "2" ]; then
    echo "Usage:     $SCRNAME <n_points> <note>"
    echo $ERRPREF "wrong number of arguments" | $LOGGER
    exit 1
fi

n_frames=$1
note="$2"

# args are file_prefix, frame count, note, card (1,2,3,4,s), data mode
ACQ="mce_bias_step_acq $n_frames '$note'"
ACQ_TARGET=0

# Try to start in good health
health_clear
if [ "$?" != "0" ]; then
    echo $ERRPREF "health_clear failed!  Check MCE/DAS." | $LOGGER
    exit 1
fi

# Start acquisition
$ACQ
if [ "$?" != "$ACQ_TARGET" ]; then
    echo $ERRPREF "'$ACQ' returned error!" | $LOGGER
    exit 1
fi

# Check health, for the record
#check_reset
#if [ "$?" != "0" ]; then
#   echo $ERRPREF "check_reset returned positive" | $LOGGER
#fi

# Record keeping: time elapsed
delta_ctime=`print_elapsed $start_ctime`
echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
echo
