#!/bin/bash
#
# Applies the biases from the command line to "tes bias"
#

source $MAS_SCRIPT/mas_library.bash

script_name="$0"
bias=$1

if [ $# -lt 1 ]; then
    echo "Usage: $script_name bias_val"
    echo "   or: $script_name bias1 bias2 bias3"
    exit 1
fi

# bias_inv=`command_reply rb tes bias`
# if [ $? -ne 0 ]; then
#     echo "FAILURE : $script_name : could not read tes bias from MCE : '$bias_inv'"
#     exit 2
# fi

# bias_count=`echo $bias_inv | wc -w`
# bias_vals=`repeat_string $1 $bias_count`

if [ $# -lt 2 ]; then
    bias_output=`command_reply wb tes bias $1 $1 $1`
else
    bias_output=`command_reply wb tes bias $1 $2 $3`
fi

if [ $? -ne 0 ]; then
    echo "FAILURE : $script_name : could not write tes bias to MCE : '$bias_output'"
    exit 3
fi

