#!/bin/bash
# bias_sqrwave
# 
# modified from bias_step_acq & code from MH
# 
# JAB 20090416

[ "$1" == "" ] && echo "bias_sqrwave min max period card para" && exit 1

#use column if you use want to modulate a particular column
#
#tes bias card=9 para=32
# 1_tile testbed only!: tes bias card=8 para=33
#sq2 fb  card=8 para=32
#sq1 bias card=10 para=2
#sq1 fb  (para=31 for rc=1, card=3, for rc=2, card=4) 
#sq2 bias card=8 para=32
#sa  fb  card=7 para=32

card=$4
para=$5
#if (( $card == 9 && $para == 32 ))
#   then num=16
#else num=1
#fi
##num=2

num=16

min=$1
max=$2
period=$(($3/2))  
step=$(($max - $min))

mce_cmd -qx wb cc internal_cmd_mode 0

mce_cmd -q \
    -X "wb cc ramp_min_val $min" \
    -X "wb cc ramp_max_val $max" \
    -X "wb cc ramp_step_period $period" \
    -X "wb cc ramp_step_size $step" \
    -X "wb cc ramp_card_addr $card" \
    -X "wb cc ramp_param_id $para" \
    -X "wb cc ramp_step_data_num $num"

sleep 0.1

mce_cmd -qx wb cc internal_cmd_mode 2