#!/bin/bash
## source ~mce/mas_env.bash
if [ $# -lt 1 ]; then
  echo "Usage: bias_tess bias_val"
  exit 1
fi
echo "This script assumes bias_tes is on bc1! double check"
mce_cmd -q -x wb bc1 bias $1
if [ $? -ne 0 ]; then
  echo "FAILURE: bias_tess failed!"
  exit 2
fi

