#!/bin/csh
# This script checks whether all values of a certain parameter are set to 0
#
# Revision history:
# <date $Date: 2007/10/25 18:12:15 $>    - <initials $Author: mce $>
# $Log: check_zero,v $
# Revision 1.5  2007/10/25 18:12:15  mce
# MA can handle replies with more than 1 line and any number of values per line
# reports number of non-zero items
#
#
#
if ($#argv != 2) then
  echo "----------------"
  echo "Usage: check_zero card parameter"
  echo "       card is the target card (i.e. rc1)"
  echo "       parameter is the parameter to check (i.e. sa_bias)"
  echo "This script checks whether the parameter is set to 0 and returns 1, otherwise it returns 0"
  echo "Warning: This script has no error checking and if mcecmd fails, you will not know!"
  echo "----------------"
  exit 2
endif  

set cmd=($argv)
set card=$cmd[1]
set param=$cmd[2]

@ cmdstatus =0
set val=`mce_cmd -qpx rb $card $param|awk '{for (i=3; i<= NF; i=i+1) if ($i != 0) sum +=1} END {print sum}'`
if ($val) then
  echo "Number of non-zero items: $val"
  exit 1
else
  echo "All items are set to 0!"
  exit 0
endif
