#!/bin/bash
#
# The output of this file should be appended to the .run file
# Use, e.g.
#    frameacq_stamp 1 outfile 10000 >> outfile.run
#  OR better
#    frameacq_stamp 1 outfile 10000 | tee -a outfile.run
#

runfile_version=2

if [ $# -ne 3 ]; then
    echo "Invalid frameacq_stamp arguments!  The arguments were:"
    echo "   $@"
    echo "Usage:"
    echo "         frameacq_stamp rc_num data_filename num_frames"
    echo
    exit 1
fi

rc="$1"
if [ "$rc" == "s" ]; then
    rc="1 2 3 4"
fi
data_filename="$2"
data_framecount="$3"

array_id=`cat /data/cryo/array_id`
mas_version=`mce_cmd -v`

ctime=`date +%s`
hostname=`hostname`

fileseq_on=0
fileseq_format=0
fileseq_interval=0

echo "<FRAMEACQ>"

echo "  <RUNFILE_VERSION> $runfile_version"
echo "  <MAS_VERSION> $mas_version"
echo "  <ARRAY_ID> $array_id"
echo "  <RC> $rc"
echo "  <DATA_FILENAME> $data_filename"
echo "  <DATA_FRAMECOUNT> $data_framecount"
echo "  <CTIME> $ctime"
echo "  <HOSTNAME> $hostname"

if [ $fileseq_on -ne 0 ]; then
    echo "  <FILESEQ_FORMAT> $fileseq_format"
    echo "  <FILESEQ_INTERVAL> $fileseq_interval"
fi

echo "</FRAMEACQ>"
echo
