#!/bin/tcsh
#
# why do I use csh?
#
# The output of this file should be appended to the .run file
# Use, e.g.
#    frameacq_stamp 1 outfile 10000 >> outfile.run
#  OR better
#    frameacq_stamp 1 outfile 10000 | tee -a outfile.run
#

set runfile_version=2

if ($#argv != 3) then
  echo "Invalid frameacq_stamp arguments!  The arguments were:"
  echo "$argv"
  echo "Usage:\n"
  echo "         frameacq_stamp rc_num data_filename num_frames"
  echo
  exit 1
endif

set rc="$argv[1]"
if ( "$rc" == "s" ) then
	set rc="1 2 3 4"
endif
set data_filename="$argv[2]"
set data_framecount="$argv[3]"

set array_id=`cat /data/cryo/array_id`

set fileseq_on=0
set fileseq_format=0
set fileseq_interval=0

echo "<FRAMEACQ>"

echo "  <RUNFILE_VERSION> $runfile_version"
echo "  <MAS_VERSION> n"
echo "  <ARRAY_ID> $array_id"
echo "  <RC> $rc"
echo "  <DATA_FILENAME> $data_filename"
echo "  <DATA_FRAMECOUNT> $data_framecount"

if ($fileseq_on) then
  echo "  <FILESEQ_FORMAT> $fileseq_format"
  echo "  <FILESEQ_INTERVAL> $fileseq_interval"
endif

echo "</FRAMEACQ>"
echo
