#!/bin/bash

# initialise environment
eval `${MAS_CONFIG:-/usr/mce/bin/mas_config} -s`

source $MAS_SCRIPT/mas_library.bash

if [ "$#" != "2" ]; then
   echo "Usage:   $0 <dead-dets-list> <level>"
   echo ""
   echo "The detectors listed in dead-dets-list will have their servo gaini parameter set to 0, immediately."
   echo "The file would look like this to turn off r00c05 and r01c16 at level 2:"
   echo "##  rc    row sa_chan level 
   echo "     1      0       5     2"
   echo "     3      1       0     2"
   echo "Comments preceeded by # or ## are ignored."
   exit 1
fi

TARGET='mce_cmd -q'
# TARGET='cat'

listfile=$1
cut_level=$2

awk '($1 != "#" && $1 != "##") {print $0}' $listfile | while read rc row chan level; do
    if [ $level -le $cut_level ]; then
        #printf "Cutting r%02ic%02i (rc%i)\n" $row $(( $chan + $rc * 8 - 8 )) $rc
	echo wra rc$rc gaini$chan $row 0	
    fi
done | $TARGET

echo "wb rca flx_lp_init 1" | $TARGET
