#!/bin/bash
#
# loopover_pixels_squidnoise dir
#

source $MAS_SCRIPT/mas_library.bash

mce_cmd -qx wb cc internal_cmd_mode 0

for (( irow = 0 ; irow < 33 ; irow++ ))
do

echo "row="$irow

mce_reconfig
sleep 1
~/python_tools/really_freeze_servo.py -r $irow --o
sleep 1

for (( icol = 0 ; icol < 16 ; icol++ ))
do

if (($icol < 8)); then rc=1; else rc=2; fi
rccol=$(($icol -8*($rc-1)))

extn='row'$irow'_col'$icol

for (( i = 0 ; i < 10 ; i++ ))
do

mce_raw_acq_1col $rc $rccol 65536 $extn $1

sleep 1
mce_cmd -qx dsp_reset

done

done
done