#!/bin/bash

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

this_array=$(cat $MAS_DATA_ROOT/array_id)

if [ "$this_array" == "" ] || [ "$this_array" == "default" ]; then
    expt=$MAS_CONFIG/experiment.cfg
    array=$MAS_CONFIG/array.cfg
else
    expt=$MAS_CONFIG/experiment_${this_array}.cfg
    array=$MAS_CONFIG/array_${this_array}.cfg
fi

gain_mask=$MAS_CONFIG/blank_mask.cfg

mas_param -s $expt  idl_template exp_params > $MAS_IDL/load_exp_params.pro
mas_param -s $array idl_template array_params  > $MAS_IDL/load_array_params.pro
mas_param -s $gain_mask idl_template mask_params > $MAS_IDL/load_mask_params.pro
