#!/bin/bash

this_array=`cat /data/cryo/array_id`

if [ "$this_array" == "" ]; then
    expt=$MAS_TEMPLATE/experiment.cfg
    array=$MAS_TEMPLATE/array.cfg
else
    expt=$MAS_TEMPLATE/experiment_${this_array}.cfg
    array=$MAS_TEMPLATE/array_${this_array}.cfg
fi

mas_param -s $expt  idl_template exp_params > $MAS_IDL/load_exp_params.pro
mas_param -s $array idl_template array_params  > $MAS_IDL/load_array_params.pro
