#!/bin/bash

function get {
    shift 1
    if [ "$1" == "" ]; then
	echo "$0: Argument required!" >&2
	return 1
    fi
    grep "^$1 *:"  $cfg_file | cut -d ':' -f 2-
    return $?
}

function set {
    shift 1
    if  [ "$2" == "" ]; then
	echo "$0: Arguments required!" >&2
	return 1
    fi
    
    param=$1
    shift 1

    # Use $* here and not $@, which will loop over arguments!
    cmd=`printf "s/$param:.*/%-30s$*/g" "$param:"`
    # echo "$cmd"
    sed -i "$cmd" $cfg_file
}

function cpp_output {
    shift 1
    cat $cfg_file | tr [a-z] [A-Z] | \
    awk "$filt_string {sub(/:/,\" \"); printf \"#define %-30s \", \$1; \$1=\"\"; print \$0;}"
}    

function bash_output {
    shift 1
    cat $cfg_file | \
	awk "$filt_string {sub(/:/,\" \"); printf \"%s=\", \$1; \$1=\"\"; printf \"( %s )\\n\", \$0;}"
}

function csh_output {
    shift 1
    cat $cfg_file | \
	awk "$filt_string {sub(/:/,\" \"); printf \"set %s = \", \$1; \$1=\"\"; printf \"( %s )\\n\", \$0;}"
}

#    cat $cfg_file |  \
#	awk "$filt_string {sub(/:/,\" \"); printf \"%s = [\", \$1; for (i=2; i<NF; i++) printf \"%s, \", \$i; print \$NF, \"]\"}"

function idl_template {

    shift 1

    echo pro load_$idl_name,filename,m

    load_string=" \
	spawn,'mas_param get %s',r,exit_status=status\n \
	if status eq 0 then begin\n \
	  %s = fix(strsplit(r,/extract))\n \
	endif else begin\n \
	  print,'Failed to load parameter %s\n \
	endelse\n"

    cat $cfg_file |  \
	awk "$filt_string {sub(/:/,\" \"); printf \"$load_string\", \$1, \$1, \$1; "}

    echo -ne "\n        m = create_struct('source',filename "
    cat $cfg_file | \
	awk "$filt_string {sub(/:/,\" \"); printf \", '%s',%s\", \$1, \$1 }"
    echo -e ")\nend\n\n"

    save_string=" \
        spawn,'mas_param set %s '+string(m.%s)\\n"
    echo pro save_$idl_name,m,filename
    cat $cfg_file |  \
	awk "$filt_string {sub(/:/,\" \"); printf \"$save_string\", \$1, \$1; "}
    echo -e "end\n"
}    


# Main program

if [ "$MAS_ROOT" == "" ]; then
	source /home/mce/mas_env.bash
fi
source $MAS_SCRIPT/mas_library.bash

cfg_file=/etc/mce/experiment.cfg    # default source file
cfg_align=20                        # alignment column
idl_name="mas_param"       # idl function names will be load_... and save_...


# Process -x style options
while getopts "f:i:" OPTION; do
    case $OPTION in

	f ) cfg_file=$OPTARG
	;;

	i ) idl_name=$OPTARG
	;;

	* ) echo "I don't know the argument '-$Option'"
    esac
done
shift $(( $OPTIND - 1 ))

# Remove commented and empty lines
filt_string='!/^ *#/ && NF>=1'

case "$1" in

    get) get $@
    ;;
    
    set) set $@
    ;;

    cpp) cpp_output $@
    ;;

    bash) bash_output $@
    ;;
    
    csh) csh_output $@
    ;;
    
    idl_template) idl_template $@
    ;;
    
    *) echo "Usage: $0 [get param | set param 'vals...']"
esac
