#!/bin/bash

source ${MAS_SCRIPT}/mas_library.bash

function check_card_life {
    results=`mce_cmd -qpx rb sys num_rows`
    if [ "$?" != "0" ]; then
        echo "life error: $results"
	return 1
    fi
#    results=`command_reply rb sys num_rows`
    echo -n $results
    for r in $results; do
	if [ "$r" == "0" ]; then
	    return 1
	fi
    done
    return 0
}	

# Stop frame data and terminate acquisitions
echo Resetting MCE
mce_cmd -qx mce_reset
sleep 1
echo Resetting PCI card
mce_cmd -qx dsp_reset
echo Issuing fakestop for acq programs
mce_cmd -qx fakestop
sleep 1
echo Emptying buffer in case there were no acq programs...
mce_cmd -qx empty


#Check card life
tries=3
[ "$1" != "" ] && tries=$1

for a in `seq 1 $tries`; do
    mce_cmd -qx mce_reset
    sleep 0.2
    check_card_life
    if [ "$?" == "1" ]; then
	echo "check_card_life failed $a"
	ok=0
    else
	ok=1
    fi
    echo $a
done

if [ "$ok" != "1" ]; then
    echo "MCE reset failed."
    exit 1
fi

echo "MCE reset Successful."
exit 0
