#!/bin/bash 

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

source $MAS_SCRIPT/mas_library.bash

expt=$MAS_DATA/experiment.cfg

if [ "$1" != "no_reset" ]; then
    echo "Resetting MCE..."
    mce_reset_clean
    clear_on_warm=`mas_param -s $expt get clear_config_on_warm | sed 's/\ //g'`
    if [ "$clear_on_warm" == "1" ]; then
	echo "Removing $expt if it exists."
	[ -e $expt ] && rm $expt
    fi
    echo "Setting current_data directory..."
    set_directory
fi

mux11d=`mas_param -s $expt get hardware_mux11d | sed 's/\ //g'`
echo x${mux11d}x

echo "Setting SA bias to default values."
sa_bias=`mas_param -s $expt get default_sa_bias`
sa_reply=`command_reply wb sa bias $sa_bias`
echo -n "SA biases:  "
command_reply rb sa bias

if [ "$mux11d" != "1" ]; then
    echo "Setting SQ2 bias to default values."
    s2_bias=`mas_param -s $expt get default_sq2_bias`
    s2_reply=`command_reply wb sq2 bias $s2_bias`
    echo -n "SQ2 biases: "
    command_reply rb sq2 bias
else
    echo "mux11d active, no SQ2."
    s2_reply=""
fi

[ "$sa_reply" == "" ] && [ "$s2_reply" == "" ] || exit 1

