#!/bin/bash

# First argument can override the experiment config file.

expt="${MAS_DATA}/experiment.mce"

if [ "$1" != "" ]; then
    expt="$1"
else
    echo "Using default configuration file, $exp!" >&2
fi

outfile=$MAS_DATA/config_mce_x
if [ -e "$outfile" ]; then
    rm $outfile
fi

# Do the shell define line explicitly
echo "#!/bin/bash" >> $outfile

# Start with header
cat ${MAS_TEMPLATE}/config_header.bash >> $outfile

# Write MCE variables
mas_param bash $expt >> $outfile

# Set the output MCE script name
echo "mce_script=$MAS_TEMP/config_mce.scr" >> $outfile

# Create the output MCE script
cat ${MAS_TEMPLATE}/config_create.bash >> $outfile

# Run the output MCE script
cat ${MAS_TEMPLATE}/config_run.bash >> $outfile
