#!/bin/bash

# Fills the user-controlled words in data frame header.  The ctime is
# put in 'run_id' and 'user_word' is a mix of the data mode and the
# array_id code.

source $MAS_SCRIPT/mas_library.bash

# Copy data mode for card $1 (eg '1' or 's') into bits 15:8
# and array_id into bits 7:0 of cc user_word

case "$1" in
    1 | 2 | 3 | 4)
	rc=$1
	;;
    *)
	rc=1
esac

data_mode=`command_reply rb rc$rc data_mode`
array_id=`cat /data/cryo/array_id`
prog="(\$1==\"${array_id}\") {print \$2}"
array_integer=`awk "${prog}" $MAS_TEMPLATE/array_list`

[ "$array_integer" != "" ] || array_integer=0

mce_cmd -qX "wb cc user_word $(( array_integer + 256 * $data_mode ))"

# Put current ctime into run_id

ctime=`print_ctime`
mce_cmd -qx wb cc run_id $ctime
