#!/bin/bash

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

source $MAS_SCRIPT/mas_library.bash

# Get some frames...
filename=`print_ctime`_sync
mce_run $filename 1000 s

eat_packets -n 4400 -f $MAS_DATA/$filename > /dev/null
err=$?

if [ "$?" != 0 ]; then
    echo 'Sync number check failed!'
    exit 1
fi

echo 'Sync check ok.'
