#!/bin/bash

CD=`cat /data/cryo/current_data_name`

CONFIG=/data/cryo/current_data/config_mce_auto_setup_${CD}
EXPT=/data/cryo/current_data/experiment.cfg

if [ ! -e $CONFIG ]; then
    echo "$CONFIG not found, retune or recover manually from previous day's settings."
    exit 1
fi

echo Running $CONFIG
$CONFIG

# Only mess with TES if tes_bias_do_reconfig=1.
do_tes=`mas_param -s $EXPT get tes_bias_do_reconfig`
if [ "$do_tes" == "1" ]; then
    BIAS=/data/cryo/tes_bias_recommended
    norm_bias=`mas_param -s $EXPT get tes_bias_normal`
    norm_time=`mas_param -s $EXPT get tes_bias_normal_time`

    echo Biasing tes normal...
    bias_tess $norm_bias
    sleep $norm_time
    echo Biasing tes to recommended values.
    $BIAS
fi
