#!/bin/bash

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

CD=$(cat ${MAS_DATA_ROOT}/current_data_name)

CONFIG=${MAS_DATA}/config_mce_auto_setup_${CD}
EXPT=${MAS_DATA}/experiment.cfg

if [ ! -e $CONFIG ]; then
    echo "$CONFIG not found, retune or recover manually from previous day's settings."
    exit 1
fi

mce_check_init

echo Running $CONFIG
$CONFIG || exit 1

# Only mess with TES if tes_bias_do_reconfig=1.
do_tes=`mas_param -s $EXPT get tes_bias_do_reconfig | sed 's/\ //g'`
echo x${do_tes}x
if [ "$do_tes" == "1" ]; then
    last_iv=${MAS_DATA_ROOT}/last_iv.out
    echo $last_iv
    if ! [ -e $last_iv ]; then
	echo Could not find last IV analysis file $last_iv 
	exit 1
    fi
    #BIAS=${MAS_DATA_ROOT}/tes_bias_recommended
    norm_bias=`mas_param -s $EXPT get tes_bias_normal`
    norm_time=`mas_param -s $EXPT get tes_bias_normal_time`

    echo Biasing tes normal...
    bias_tess $norm_bias
    sleep $norm_time
    echo Biasing tes to recommended values.
    auto_iv bias $last_iv || ( \
	echo "auto_iv failed to set bias."
	exit 1
    )
fi
