#!/bin/bash

source $MAS_ROOT/mas_env.bash

# Note to self: learn perl

if [ "$1" == "" ]; then
    echo "Usage:    mcestatus <filename>"
    exit 1
fi

FOUT=$1

echo "<HEADER>" >> $FOUT

mce_cmd -q -f ${MAS_SCRIPT}mcestatus.mcebat | \
    while read line; do
        words=( $line )
	if [ "${words[3]}" == "#" ]; then
	    continue
	fi

	case "${words[0]}" in

	Cmd)
	    printf "<%s %s %s>" ${words[3]} ${words[4]} ${words[5]}
	    ;;

	Line)
	    for a in `seq 5 $(( ${#words[@]} - 1 ))`; do
		printf " %08i" ${words[$a]}
	    done
	    printf "\n"
	    ;;

	esac
    done >> $FOUT

cmd_err=${PIPESTATUS[0]}
if [ "$cmd_err" != "0" ]; then
    echo -e "mcestatus script failed with code $cmd_err\n" >&2
    exit $cmd_err
fi

echo "</HEADER>" >> $FOUT
