#!/bin/bash
#
# This is the script to take superfast noise data through the transition on BICEP2.
#
#
# JAB 20090715 noise_superfast_1tile original
# JAB 20091001 noise_superfast mod for BICEP2

source $MAS_SCRIPT/mas_library.bash

if [ "$#" -lt "1" ]; then
    echo "Usage:   noise_superfast dir"
    exit 1
fi

echo "you are using noise_superfast"

dir=$1

# Don't fiddle with tes bias when using mce_reconfig in 'really_freeze_servo.py'
mas_param set tes_bias_do_reconfig 0
mas_param set sq1_bias_off 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
mce_make_config
mce_reconfig                                         #20091016 JAB added to fix sq2fb-tesbias xtalk issue

#for tbias in 2800
for (( tbias=4600; tbias>=2600; tbias=$tbias-200 ))
do

dir=$1'/bias'$tbias'/'
mkdir '/data/cryo/current_data/'$1/'bias'$tbias'/'

bias_tess $tbias

sleep 30

#for (( row=0; row<=33; row=$row+1 ))
for row in 8 9 24 25
#for row in 5 10 15 20 25 30
do

echo 'row='$row

## light pixels all tiles Run8.0
case "$row" in
     5 ) coluse=( 0 2 4 6 8 12 15 ) ;;
     8 ) coluse=( 0 8 ) ;;
     9 ) coluse=( 0 8 ) ;;
     10 ) coluse=( 0 3 5 7 8 9 11 13 ) ;;
     15 ) coluse=( 0 1 2 4 6 7 10 12 15 ) ;;
     20 ) coluse=( 0 1 3 9 10 11 13 15 ) ;;
     24 ) coluse=( 15 ) ;;
    # 25 ) coluse=( 0 2 4 5 6 8 10 12 ) ;;
     25 ) coluse=( 15 ) ;;
     30 ) coluse=( 0 1 3 5 7 9 11 13 ) ;;
esac

## light pixels tiles 1,3 & 4 Run7.0 hienostat
##case "$row" in
##     8 ) coluse=( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ) ;;
##     9 ) coluse=( 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 ) ;;
##     20 ) coluse=( 1 9 11 ) ;;
##     25 ) coluse=( 0 2 3 8 10 12 13 14 15 ) ;;
##esac

##case "$col" in
##    3 ) rowuse=( 0 4 18 24 25 32 ) ;;
##    14 ) rowuse=( 11 ) ;;
##    15 ) rowuse=( 12 13 28 29 ) ;;
##esac

for col in ${coluse[@]}
do

echo 'col='$col

##for row in ${rowuse[@]}
##do

if [ $col -lt 8 ]; then
    rc=1
else
    rc=2
fi

mce_reconfig
~/python_tools/really_freeze_servo.py -r $row --o        #JAB 20091001 really_freeze_servo.py moved to ~/python_tools/

fb_val=(`mce_cmd -qrx rb sq1 fb_const`)
echo 'fb_val= '${fb_val[@]}
#sleep 1

# take super-fast noise timestreams at 400kHz, sampling pixel of interest
#
filename=$dir'/superfast_row'$row'_col'$col
superfast_acq $col $row 12000000 $filename                 #JAB 20091007 commented out, this gives 320,000samples, 12.8sec
#superfast_acq $col $row 781250 $filename                  #JAB 20091007 this gives 25,000,000samples, 100sec=10mHz
#name='rawacq_row'$row'_col'$col                         #JAB 20091001 removed for run5 testing
#mce_raw_acq_1col $rc $col 65536 $name $dir
sleep 2
mce_cmd -x dsp_reset

stepsize=10
index=$((5+8*($rc-1)+$col))
extn=$dir'calib_row'$row'_col'$col
min=$((${fb_val[$index]}-$stepsize))
max=$((${fb_val[$index]}+$stepsize))

sleep 2
fb1const_sqrwave $min $max 50 $rc
sleep 3
mce_cmd -x dsp_reset
rectmode_15kHz_acq 10000 $rc $extn                        #20091016 JAB added to replace mce_fast_acq sampling with rect_mode 15kHz sampling
sleep 1

mce_cmd -x wb cc internal_cmd_mode 0

##mce_reconfig

done
done
done

mce_reconfig