#!/bin/csh 
#
# Revision history:
# <date $Date: 2007/05/23 18:34:19 $>    - <initials $Author: mce $>
# $Log: pidz_dead_off,v $
# Revision 1.2  2007/05/23 18:34:19  mce
# elia: now no columns are set to dead as default
#
# Revision 1.1  2007/05/16 18:44:32  mce
# sets PID coefficients for dead columns to 0
#
# Revision 1.4  2006/02/09 06:17:18  mce
# Bryce: added rc_num as an argument, removed zero0 to zero7 commands
#
# Revision 1.3  2005/11/10 20:08:35  mandana
# added cvs revision log header
# 
#
source tmas_env
if ($#argv < 4 ) then
  echo "----------------"
  echo "Usage: pidz p i d rc_num"
  echo "where: p is the p coefficient of pidz controller"
  echo "       i is the i coefficient of the pidz controller"
  echo "       d is the d coefficient of the pidz controller"
  echo "       rc_num is 1, 2, 3, 4, or s for all"
  echo "Note: this script sets the p, i, d for all channels and all rows"
  echo "Note 2: p, i, d, are applied to sum(sample-adc_offset)"
  exit 1
endif  
/bin/rm $MAS_TEMP/pidz_dead.temp
@ i=0
while ( $i<8 )
  echo "wb rc$4 gainp$i $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1 $1">>$MAS_TEMP/pidz_dead.temp

  echo "wb rc$4 gaini$i $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2">>$MAS_TEMP/pidz_dead.temp

  echo "wb rc$4 gaind$i $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3">>$MAS_TEMP/pidz_dead.temp
  @ i++
end
mce_cmd -f $MAS_TEMP/pidz_dead.temp

