#!/bin/bash
# Revision history:
# <date $Date: 2007/10/04 05:32:45 $>    - <initials $Author: preaction $>
# $Log: pidz_ch,v $
# Revision 1.3  2007/10/04 05:32:45  preaction
# MA added mcebatchgo error message
#
source ~mce/mas_env.bash

TEMPFILE="pidz.temp"

if [ "$#" -lt 6 ] ; then
  echo "----------------"
  echo "Usage: pidz_ch ch_num p i d adc_offset rc_num"
  echo "where: ch_num is the column number [0 to 7]"
  echo "       p is the p coefficient of pidz controller"
  echo "       i is the i coefficient of the pidz controller"
  echo "       d is the d coefficient of the pidz controller"
  echo "       adc_offset is the value that is deducted from every 50MHz sample"
  echo "       rc_num is the number of the readout card to be initialized [1 to 4]"
  echo "Note: this script sets the p, i, d, adc_offset for all rows of the particular column"
  echo "Note 2: p, i, d coefficients are applied to sum[sample-adc_offset]"
  exit 1
fi
/bin/rm $MAS_TEMP/$TEMPFILE

echo "wb rc$6 gainp$1 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2 $2">>$MAS_TEMP/$TEMPFILE

echo "wb rc$6 gaini$1 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3 $3">>$MAS_TEMP/$TEMPFILE

echo "wb rc$6 gaind$1 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4 $4">>$MAS_TEMP/$TEMPFILE

echo "wb rc$6 adc_offset$1 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5 $5">>$MAS_TEMP/$TEMPFILE
mce_cmd -f $MAS_TEMP/$TEMPFILE 
if [ "$?" -ne 0 ] ; then
  echo "FAILURE: mcebatchgo in pidz_ch failed"
  exit 2
fi
