#!/bin/tcsh 
#
# Revision history:
# <date $Date: 2007/10/22 16:24:46 $>    - <initials $Author: preaction $>
# $Log: pidz_dead_off,v $
# Revision 1.3  2007/10/22 16:24:46  preaction
## source ~mce/mas_env.tcsh

if ($#argv < 3 ) then
  echo "----------------"
  echo "Usage: pidz_dead_off p i d"
  echo "where: p is the p coefficient of pidz controller"
  echo "       i is the i coefficient of the pidz controller"
  echo "       d is the d coefficient of the pidz controller"
  echo "       n is the rc number"
  echo "Note: this script sets the p, i, d for all rows of all channels of specified RC"
  echo "    This is the script where individual detectors with bad SQUIDs can be turned off"
  echo "Note 2: p, i, d, z coefficients are applied to sum(sample-adc_offset)"
  exit 1
endif  

@ card = $4

@ pid_no=0
while ($pid_no < 3)
  if ($pid_no == 0) then
	set f=p
	set n=$1
  endif
  if ($pid_no == 1) then
	set f=i
	set n=$2
  endif
  if ($pid_no == 2) then
	set f=d
	set n=$3
  endif
  
  if ( $card == 1) then 
  #     Columns 00-07
  #     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
    echo "wb rc1 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc1 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
  endif
  
  if ( $card == 2 ) then
  #     Columns 08-15
  #     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
 #   echo "wb rc2 gain"$f"0 0 0 0 0 $n 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
    echo "wb rc2 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc2 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
  endif
  
  if ( $card == 3 ) then
  #     Columns 16-23
  #     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
    echo "wb rc3 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc3 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
  endif
  
  if ( $card == 4 ) then
  #     Columns 24-31
  #     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
    echo "wb rc4 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
    echo "wb rc4 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n"
  endif
  @ pid_no++
end
  
