#!/bin/tcsh 
#
# Revision history:
# <date $Date: 2007/10/22 16:24:46 $>    - <initials $Author: preaction $>
# $Log: pidz_dead_off,v $
# Revision 1.3  2007/10/22 16:24:46  preaction
#
#  Modified Files:
#  	auto_acquire config_mce_auto_setup_template dredge_fifo
#  	pidz_dead_off ramp_sq1_bias ramp_sq1_fb ramp_tes_bias
#  	set_directory
#
# Scripts modified prior to first light observations with MBAC on 10-22-07.
# MN & EB
#
# Revision 1.2  2007/09/11 16:27:03  preaction
#
#  Modified Files:
#  	adc_offset_auto bias_tess chopper_remote_control
#  	config_mce_auto_setup_template mceframeacq pidz_dead_off
#  	ramp_tes_bias scripted_noise set_directory setdata sq1servo
#  	mux_lock/sq1servo mux_lock/sq1servo.c
#  Added Files:
#  	bias_step_run
#
# Committing all to CVS 9-11-2007 MDN
#
# S: ----------------------------------------------------------------------
#
# Revision 1.1.1.1  2007/09/02 19:50:14  preaction
# first commit of MCE DAS scripts for MBAC
#
# Revision 1.2  2007/05/23 18:34:19  mce
# elia: now no columns are set to dead as default
#
# Revision 1.1  2007/05/16 18:44:32  mce
# sets PID coefficients for dead columns to 0
#
# Revision 1.4  2006/02/09 06:17:18  mce
# Bryce: added rc_num as an argument, removed zero0 to zero7 commands
#
# Revision 1.3  2005/11/10 20:08:35  mandana
# added cvs revision log header
# 
# Revision 1.6  2007/08/31 13:50 M. Niemack
# Changed to loop format and to handle an entire 32x32 array
# Removed z, adc_offset, and rc parameters from inputs.
#
source ~mce/mas_env.tcsh

set TEMPFILE="pidz.temp"

if ($#argv < 3 ) then
  echo "----------------"
  echo "Usage: pidz_dead_off p i d"
  echo "where: p is the p coefficient of pidz controller"
  echo "       i is the i coefficient of the pidz controller"
  echo "       d is the d coefficient of the pidz controller"
  echo "Note: this script sets the p, i, d for all channels and all rows"
  echo "    This is the script where individual detectors with bad SQUIDs can be turned off"
  echo "Note 2: p, i, d, z coefficients are applied to sum(sample-adc_offset)"
  exit 1
endif  

/bin/rm $MAS_TEMP/$TEMPFILE

@ pid_no=0
while ($pid_no < 3)
  if ($pid_no == 0) then
	set f=p
	set n=$1
  endif
  if ($pid_no == 1) then
	set f=i
	set n=$2
  endif
  if ($pid_no == 2) then
	set f=d
	set n=$3
  endif
#     Columns 00-07
#     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
  echo "wb rc1 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc1 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE


#     Columns 08-15
#     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
  echo "wb rc2 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc2 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE

#     Columns 16-23
#     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
  echo "wb rc3 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc3 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE

#     Columns 24-31
#     row number         00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 - - - - - - - -
  echo "wb rc4 gain"$f"0 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"1 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"2 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"3 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"4 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"5 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"6 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE
  echo "wb rc4 gain"$f"7 $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n $n">>$MAS_TEMP/$TEMPFILE

  @ pid_no++
end

mce_cmd -q -f $MAS_TEMP/$TEMPFILE
if ($status) then
  echo "pidz_dead_off: mce_cmd failed!"
  exit 2
endif
