#!/usr/bin/python

import os
import auto_setup as ast
from optparse import OptionParser

usage = """
%prog [options] tuning_directory [output_directory]

If output_directory is ommitted, ./ is used.
"""

o = OptionParser(usage=usage)
o.add_option('-i','--interactive',action='store_true',default=False)
o.add_option('-s','--stage',action='append',default=None)
o.add_option('--summary',action='store_true',default=False,help=
             "For bias ramps, plot only the final bias choice.")
o.add_option('-m','--format',default=None,help=
             "Set output format (png, svg, pdf).")
o.add_option('--default-slope', type='float', default=None)
o.add_option('--config-file', default=None)
opts, args = o.parse_args()

if len(args) > 2 or len(args) <= 0:
    o.error('Pass 1 or 2 arguments.')

odir = './'
if len(args) == 2:
    odir = args[1]

source_dir = args[0]
basename = source_dir.strip('/').split('/')[-1]
# Try '/home/data/act/2010/startup/1269227063/'

if opts.interactive:
    ast.util.interactive_errors()

if not os.path.exists(odir):
    os.makedirs(odir)

default_ops = ['sa_ramp', 'sq2_servo', 'sq1_servo', 'sq1_ramp',
               'sq1_ramp_check', 'sq1_ramp_tes']

if opts.stage == None:
    opts.stage = default_ops
else:
    for op in opts.stage:
        if not op in default_ops:
            print 'Unknown stage "%s" ignored.' % op

# Group files
tf = ast.util.FileSet(source_dir)

# Do we have an experiment.cfg?
if opts.config_file == None:
    # There's probably one with the tuning data.
    opts.config_file = tf.get('cfg_file', None)

if opts.config_file == None:
    tuning = None
else:
    tuning = ast.util.tuningData(exp_file=opts.config_file)

slope = opts.default_slope 

if slope == None and tuning == None:
    o.error("No experiment.cfg data could be found for this tuning.  Pass "
            "in a filename with --config-file, or specify a default locking "
            "slope with --default-slope.")

if 'sa_ramp' in opts.stage:
    # Load SA ramp
    ss = [ ast.SARamp(x, tuning=tuning) for x in tf.stage_all('sa_ramp') ]
    s1 = ast.SARamp.join(ss)
    s1.reduce1()
    if s1.bias_style == 'ramp':
        s2 = s1.subselect()
    else:
        s2 = s1
    s2.reduce(slope=slope)
    s2.plot(plot_file='%s/%s_sa_ramp' % (odir, basename),
            format=opts.format)

if 'sq2_servo' in opts.stage:
    ss = [ ast.SQ2Servo(x, tuning=tuning) for x in tf.stage_all('sq2_servo') ]
    s = ast.SQ2Servo.join(ss)
    if s.bias_style == 'ramp':
        if not opts.summary:
            # Plot data for every bias value
            s.plot(plot_file='%s/%s_sq2_servo' % (odir, basename),
                   format=opts.format)
            s.plot_error(plot_file='%s/%s_sq2_servo_err' % (odir, basename),
                         format=opts.format)
        # Flatten ramp to best bias choice
        s.reduce1()
        s = s.select_biases()
    s.reduce(slope=slope)
    s.plot(plot_file='%s/%s_sq2_servo' % (odir, basename),
           format=opts.format)
    s.plot_error(plot_file='%s/%s_sq2_servo_err' % (odir, basename),
                 format=opts.format)

if 'sq1_servo' in opts.stage:
    ss = [ ast.SQ1Servo(x, tuning=tuning) for x in tf.stage_all('sq1_servo') ]
    s = ast.SQ1Servo.join(ss)
    if s.bias_style == 'ramp':
        if not opts.summary:
            # Plot data for every bias value
            s.plot(plot_file='%s/%s_sq1_servo' % (odir, basename),
                   format=opts.format)
            s.plot_error(plot_file='%s/%s_sq1_servo_err' % (odir, basename),
                         format=opts.format)
        # Flatten ramp to best bias choice
        s.reduce1()
        s = s.select_biases()
    s.reduce(slope=slope)
    s.plot(plot_file='%s/%s_sq1_servo' % (odir, basename),
           format=opts.format)
    s.plot_error(plot_file='%s/%s_sq1_servo_err' % (odir, basename),
                 format=opts.format)

if 'sq1_ramp' in opts.stage:
    # Load SQ1 ramp
    ss = [ ast.SQ1Ramp(x, tuning=tuning) for x in tf.stage_all('sq1_ramp') ]
    s = ast.SQ1Ramp.join(ss)
    s.reduce()
    s.plot(plot_file='%s/%s_sq1_ramp' % (odir, basename),
           format=opts.format)

if 'sq1_rampc' in opts.stage:
    # Load SQ1 ramp
    ss = [ ast.SQ1Ramp(x, tuning=tuning) for x in
           tf.stage_all('sq1_ramp_check') ]
    s = ast.SQ1Ramp.join(ss)
    s.reduce()
    s.plot(plot_file='%s/%s_sq1_ramp_check' % (odir, basename),
           format=opts.format)

if 'sq1_ramp_tes' in opts.stage:
    ss = [ ast.SQ1RampTes(x, tuning=tuning) for x in
           tf.stage_all('sq1_ramp_tes') ]
    s = ast.SQ1RampTes.join(ss)
    s.reduce()
    s.plot(plot_file='%s/%s_sq1_ramp_tes' % (odir, basename),
           format=opts.format)
