#!/bin/bash 
#
# This script outputs the mce commands (in text form) from ramp_sa_fb
#

source ${MAS_SCRIPT}/mas_library.bash

#arguments:
n=$1
datafile=$2
nested_loop=$3
total_bias=$4
bias_step=$5
start_bias=$6
num_cols=$7

echo "acq_path $MAS_DATA"
echo "acq_config $datafile rc$n"

nbias=0
while [ "$nbias" -lt "$total_bias" ]; do
   if [ $nested_loop -eq 1 ] ; then
     j=$(( $nbias * $bias_step ))
     k=$(( $start_bias + $j ))
     m=$(( $k / 2 ))
     #echo "wb rc$n offset $m $m $m $m $m $m $m $m"
     #echo "wb rc$n sa_bias $k $k $k $k $k $k $k $k"
     repeat_string "wb rc$n offset" $m 8 ""
     repeat_string "wb rc$n sa_bias" $m 8 ""
   fi
   total=400
   nsafb=0
   while [ "$nsafb" -lt "$total" ]; do
      i=$(($nsafb * 160))
      #for ix in `seq $col_index $lastcol_index`;do 
      #  echo "wel bc1 flux_fb $ix $i"
      #done
      #echo -ne "wb bc1 flux_fb"
      #for j in `seq $num_cols`; do
      #   echo -ne " $i" 
      #done
      #echo ""

      #echo "wb bc1 flux_fb $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i"
      repeat_string "wb bc1 flux_fb" $i 16 ""
      
      echo "acq_go 1"
      (( nsafb += 1 ))
   done
   (( nbias +=1 ))
done 

# reset values
if [ $nested_loop -eq 1 ] ; then
   #echo "wb rc$n sa_bias 0 0 0 0 0 0 0 0"
   repeat_string "wb rc$n sa_bias" "0" 8 ""
   #echo "wb rc$n offset 0 0 0 0 0 0 0 0"
   repeat_string "wb rc$n offset" "0" 8 ""
fi
#echo "wb bc1 flux_fb 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0"
repeat_string "wb bc1 flux_fb" "0" 16 ""

#for ix in `seq $col_index $lastcol_index`;do 
#   echo "wel bc1 flux_fb $ix 0"
#done
#echo -ne "wb bc1 flux_fb" 
#for i in `seq $num_cols` ;do 
#   echo -ne " 0" 
#done
#echo ""
