#!/bin/bash 
#
# Revision history:
# <date $Date: 2007/10/04 05:24:56 $>    - <initials $Author: preaction $>
# $Log: ramp_sa_fb,v $
# Revision 1.3  2007/10/04 05:24:56  preaction
# MA generates runfile with <par_ramp> block
#    when no bias is specified, no bias is applied!
#    the temp file is renamed
#
# Revision 1.13  2007/09/28 23:08:14  mce
# MA generates runfile now
#

# this should set $MAS_DATA and $MAS_TEMP
source ~mce/mas_env.bash
if [ $# -lt 3 ]; then 
  echo "----------------"
  echo "Usage: ramp_sa_fb datafile n d"
  echo "where : datafile is the name of the datafile"
  echo "        n        is the rc card number (1 to 4 or s for all)"
  echo "        d        is 0 for sweeping sa_fb only and 1 for sweeping sa_fb and sa_bias/offset"
  echo "Note that the file will be saved under the data directory."
  echo "----------------"
  exit 1
fi  

start_ctime=`date -u +%s`
tempfile=$MAS_TEMP/ramp_sa_fb.temp
script_name="ramp_sa_fb"

datafile=$1
runfile=$datafile.run
n=$2
nested_loop=$3

if [ $nested_loop -eq 0 ] ; then
  total_bias=1 
  bias_step=0
else
  total_bias=25
  bias_step=1500
  start_bias=15000
fi

########################
# now create runfile
mce_status -f $MAS_DATA/$runfile
if [ $? -ne 0 ] ; then
  echo "FAILURE ($script_name: mce_status failed)"
  exit 5
fi 

#par2 is the outer loop
echo "<par_ramp>" >>$MAS_DATA/$runfile
if [ $nested_loop -eq 0 ] ; then
   echo "  <loop_list> loop1">>$MAS_DATA/$runfile
   echo "    <par_list loop1> par1">>$MAS_DATA/$runfile
   echo "      <par_title loop1 par1> sa_fb">>$MAS_DATA/$runfile
   echo "      <par_step loop1 par1> 0 160 400">>$MAS_DATA/$runfile
else
   echo "  <loop_list> loop1 loop2">>$MAS_DATA/$runfile
   echo "    <par_list loop1> par1 par2">>$MAS_DATA/$runfile
   echo "       <par_title loop1 par1> sa_bias">>$MAS_DATA/$runfile
   echo "       <par_step loop1 par1> $start_bias $bias_step $total_bias">>$MAS_DATA/$runfile
   echo "       <par_title loop1 par2> offset">>$MAS_DATA/$runfile
   echo "       <par_step loop1 par2> $start_bias $bias_step $total_bias">>$MAS_DATA/$runfile
   echo "    <par_list loop2> par1">>$MAS_DATA/$runfile 
   echo "       <par_title loop2 par1> sa_fb">>$MAS_DATA/$runfile
   echo "       <par_step loop2 par1> 0 160 400">>$MAS_DATA/$runfile
fi
echo "</par_ramp>">>$MAS_DATA/$runfile
echo "">>$MAS_DATA/$runfile

total_frames=$(( $total_bias * 400 ))
frameacq_stamp $n $datafile $total_frames>>$MAS_DATA/$runfile
if [ "$?" != "0" ] ; then
  echo "FAILURE: ($script_name: frameacq_stamp failed)"
  exit 5
fi
#########################

echo "Now running a sweep of sa_fb (0 to 400*160) for each of $total_bias bias value(s)"
#########################
# now create mcebatch file to run 
/bin/rm $tempfile

echo "acq_path $MAS_DATA">>$tempfile 
echo "acq_config $datafile rc$n">>$tempfile

nbias=0
while [ "$nbias" -lt "$total_bias" ]; do
   if [ $nested_loop -eq 1 ] ; then
     j=$(( $nbias * $bias_step ))
     k=$(( $start_bias + $j ))
     m=$(( $k / 2 ))
     echo "wb rc$n offset $m $m $m $m $m $m $m $m">>$tempfile
     echo "wb rc$n sa_bias $k $k $k $k $k $k $k $k">>$tempfile
   fi
   total=400
   nsafb=0
   while [ "$nsafb" -lt "$total" ]; do
      i=$(($nsafb * 160))
      echo "wb bc1 flux_fb $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i $i">>$tempfile 
      #echo "go rc$n ret_dat 1">>$tempfile
      echo "acq_go 1">>$tempfile
      (( nsafb += 1 ))
   done
   (( nbias +=1 ))
done 

# reset values
if [ $nested_loop -eq 1 ] ; then
   echo "wb rc$n sa_bias 0 0 0 0 0 0 0 0">>$tempfile
   echo "wb rc$n offset 0 0 0 0 0 0 0 0">>$tempfile
fi
echo "wb bc1 flux_fb 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0">>$tempfile 

mce_cmd -q -f $tempfile
if [ $? -ne  0 ] ; then
  echo "FAILURE: ($script_name: mce_cmd failed)"
  exit 4
fi

end_ctime=`date -u +%s`
elapsed=$(( $end_ctime - $start_ctime))
echo "$0 elapsed time: $elapsed s"
