#!/bin/bash

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

source $MAS_SCRIPT/mas_library.bash

if [ $# -lt 2 ]; then
    echo "This script will ramp the sq2 feedback."
    echo "SQ2 bias and SQ1 settings are not changed."
    echo ""
    echo "Usage: ramp_sq2_fb datafile n"
    echo "where: datafile is the name of the file"
    echo "       n        is the rc number (or s for all)"
    exit 1
fi

start_ctime=`print_ctime`

datafile=$MAS_DATA/$1
rc=$2
n_col=8
all_col=`command_reply rb sq2 fb | wc -w`

case "$rc" in
    1 | 2 | 3 | 4)
        col_index=$(( $rc * 8 - 8 ))
        col_count=8
	;;

    s | S)
	col_index=0
	col_count=$all_col
	;;

    *)
	echo "Invalid card specification '$rc' (must be one of 1,2,3,4 or s)"
	exit 1
esac
    
tempfile=$MAS_TEMP/`whoami`_ramp_sq2_fb.temp
runfile=$datafile.run

# SQ1 feedback ramp parameters
#expt=$MAS_DATA/experiment.cfg
#feedback_start=`mas_param -s $expt get sq1_ramp_flux_start`
#feedback_step=`mas_param -s $expt get sq1_ramp_flux_step`
#feedback_count=`mas_param -s $expt get sq1_ramp_flux_count`

feedback_start=0
feedback_step=160
feedback_count=400

n_frames=$feedback_count

[ -e $tempfile ] && /bin/rm $tempfile

# Create runfile

mce_status -f $runfile
if [ $? -ne 0 ]; then
  echo "FAILURE: ($script_name: mce_status failed)"
  exit 5
fi

# echo "<par_ramp>"  >> $runfile
# echo "  <loop_list> loop1" >> $runfile
# echo "    <par_list> loop1" >> $runfile
# echo "      <par_title loop1 par1> s1_fb" >> $runfile
# echo "      <par_step loop1 par1> $feedback_start $feedback_step $feedback_count" >> $runfile
# echo "</par_ramp>" >> $runfile

frameacq_stamp $rc $datafile $n_frames >> $runfile
if [ $? -ne 0 ]; then
  echo "FAILURE: ($script_name: frameacq_stamp failed)"
  exit 6
fi

##########################

mce_ramp \
    -M "acq_config $datafile rc$rc" \
    -L $feedback_count  -V $feedback_start $feedback_step \
    -P "wra sq2 fb $col_index " $col_count \
    -P "acq_go 1" 0 \
    -M "`repeat_string '0' $col_count \"wb sq2 fb \"`" \
    >> $tempfile

mce_cmd -q -f $tempfile
if [ $? -ne 0 ]; then
  echo "FAILURE: ($script_name: mce_cmd failed)"
  exit 4
fi

echo "$0 elapsed time: " `print_elapsed $start_ctime`
