#!/bin/bash
#
# This is the script to take 15kHz data using rectangle mode.  This is apparently more stable with v5 firmware than mce_fast_acq
# mce_fast_acq n_frames rc data_rate=1 row_reported=1 gives 15kHz spectra for one row, across 8 columns in rc specified.  This
# script duplicates that funcitonality, but allows you to specify the filename.
#
# JAB 20091016 rectmode_15kHz_acq


source $MAS_SCRIPT/mas_library.bash

if [ "$#" -lt "1" ]; then
    echo "Usage:   rectmode_15kHz_acq n_frames rc filename"
    exit 1
fi

datarate=33
row_len=100              
sampreq=$1
rc=$2
filename=$3
nsamp=$(( $sampreq/$datarate ))
sampint=( `echo $nsamp | awk '{printf "%.0f",$1}' `)

mce_cmd -qx wb sys row_len $row_len           
mce_cmd -qx wb sys num_rows 33
mce_cmd -qx wb rca num_rows_reported 1
mce_cmd -qx wb rca num_cols_reported 8
mce_cmd -qx wb cc num_rows_reported $datarate
mce_cmd -qx wb cc num_cols_reported 8
mce_cmd -qx wb cc data_rate $datarate
#mce_cmd -qx wb rca readout_row_index
sleep 2
mce_run $filename $sampint $rc
sleep 1
mce_cmd -qx dsp_reset