#!/bin/bash

if [ "$MAS_ROOT" == "" ]; then
    echo MAS_ROOT variable not set.
    exit 1
fi

source $MAS_ROOT/mas_env.bash

today=`date +%Y%m%d`
cd $MAS_DATA/..
if [ ! -e $today ]; then
    mkdir $today
    chmod g+s $today
fi
# Not necessary; folder permissions are used.
# chmod 777 $today
cd $today

cp $MAS_TEMPLATE/sabias.init .
cp $MAS_TEMPLATE/safb.init .
cp $MAS_TEMPLATE/sq2bias.init .
cp $MAS_TEMPLATE/sq2fb.init .
cp $MAS_TEMPLATE/sq1bias.init .
cp $MAS_TEMPLATE/row.init .

#chmod g+w $MAS_DATA/*.init

new_config="config_mce_auto_setup_$today"
if [ -e $new_config ]; then
  echo "There is already a config_mce_auto_setup file in this directory"
else
  cp $MAS_TEMPLATE/config_mce $new_config
fi

new_adc="config_mce_adc_offset_$today"
if [ -e $new_adc ]; then
  echo "There is already a config_mce_adc_offsets file in this directory"
else
  cp $MAS_TEMPLATE/config_mce_adc_offset $new_adc
fi

if [ ! -e analysis ]; then
    mkdir analysis
    chmod g+s $today
fi

/bin/rm /data/cryo/current_data
ln -s /data/cryo/$today  /data/cryo/current_data  

/bin/rm /data/cryo/current_data_name
echo $today > /data/cryo/current_data_name

maslog reopen
