#!/bin/bash

if [ "$MAS_ROOT" == "" ]; then
    echo MAS_ROOT variable not set.
    exit 1
fi

source $MAS_ROOT/mas_env.bash

# All our new files should be group rw
umask 002

today=`date +%Y%m%d`
cd $MAS_DATA/..
if [ ! -e $today ]; then
    mkdir $today
    chmod g+s $today
fi
cd $today

cp $MAS_TEMPLATE/sabias.init .
cp $MAS_TEMPLATE/safb.init .
cp $MAS_TEMPLATE/sq2bias.init .
cp $MAS_TEMPLATE/sq2fb.init .
cp $MAS_TEMPLATE/sq1bias.init .
cp $MAS_TEMPLATE/row.init .

cp /etc/mce/experiment.cfg .

#chmod g+w $MAS_DATA/*.init

new_config="config_mce_auto_setup_$today"
if [ -e $new_config ]; then
  echo "There is already a config_mce_auto_setup file in this directory"
else
  cp $MAS_TEMPLATE/config_mce $new_config
  chmod u+rwx $new_config
  chmod g+rws $new_config
fi

new_adc="config_mce_adc_offset_$today"
if [ -e $new_adc ]; then
  echo "There is already a config_mce_adc_offset file in this directory"
else
    touch $new_adc
    chmod u+rwx $new_adc
    chmod g+rws $new_adc
fi

if [ ! -e analysis ]; then
    mkdir analysis
    chmod g+s $today
fi

/bin/rm /data/cryo/current_data
ln -s /data/cryo/$today  /data/cryo/current_data  

/bin/rm /data/cryo/current_data_name
echo $today > /data/cryo/current_data_name

maslog reopen
