#!/bin/bash

# Executes a script, without arguments, in an auto context.
#

# initialise environment
eval `${MAS_CONFIG:-/usr/mce/bin/mas_config} -s`

source $MAS_SCRIPT/mas_library.bash

if [ $# -lt 1 ]; then
    echo "Usage:   $0 <caller_name> <script> [args]"
    echo " args let you log things, not pass arguments to the script. Supported:"
    echo "  --tes-before    log the TES biases before running the script"
    echo "  --tes-after     log the TES biases after running the script"
    exit 1
fi

SCRNAME="$1"
COMMAND="$2"

AUTO_LOG=$MAS_DATA/auto_log.txt
LOGGER="tee -a $AUTO_LOG"

ERRPREF="ERROR : $SCRNAME :"

start_time=`date`
start_ctime=`print_ctime`

echo "START : $SCRNAME : $start_time" | $LOGGER

# Pre-logging
for a in $@; do
    case "$a" in
	"--tes_before")
	    tes_biases=`command_reply rb tes bias`
	    echo "INFO  : $SCRNAME : tes bias before = '$tes_biases'" | $LOGGER
	    ;;

	*)
	    ;;
    esac
done

$COMMAND
error=$?

# Post-logging

for a in $@; do
    case "$a" in

	"--tes_after")
	    tes_biases=`command_reply rb tes bias`
	    echo "INFO  : $SCRNAME : tes bias after = '$tes_biases'" | $LOGGER
	    ;;

	*)
	    ;;
    esac
done

# Record keeping: time elapsed
delta_ctime=`print_elapsed $start_ctime`

if [ "$error" != "0" ]; then
    echo "ERROR : $SCRNAME : time elapsed = $delta_ctime . '$COMMAND' returned code $error."
    exit 1
fi
echo "STOP  : $SCRNAME : time elapsed = $delta_ctime" | $LOGGER
