#!/bin/bash
#
# This is the script to take superfast data on BICEP2.
#
#
# JAB 20090715 superfast_1tile original
# JAB 20091001 superfast_acq mod for BICEP2.

source $MAS_SCRIPT/mas_library.bash

if [ "$#" -lt "1" ]; then
    echo "Usage:   superfast_acq col row nsamp filename"
    exit 1
fi

row_len=98                         #row_len=31 gives ~800kHz, row_len=62 gives ~400kHz sampling, row_len=100 gives ~250kHz
ccnumrows=33                       
ccnumcols=8
datarate=$(( $ccnumrows * $ccnumcols ))
col=$1
row=$2
nsamp=$3
filename=$4
if [ $col -lt 8 ]; then 
    rc=1 
else 
    rc=2
fi

samplenum=10
sampledly=$(( $row_len-$samplenum )) 

sampleuse=$(( $nsamp/$ccnumrows/$ccnumcols ))
sampint=( `echo $sampleuse | awk '{printf "%.0f",$1}' `)

mce_cmd -qx wb sys row_len $row_len                   #added 20091016 JAB for readout rate adj
mce_cmd -qx wb rca sample_dly $sampledly
mce_cmd -qx wb rca sample_num $samplenum
mce_cmd -qx wb sys num_rows 33
mce_cmd -qx wb rca num_rows_reported 1
mce_cmd -qx wb rca num_cols_reported 1
mce_cmd -qx wb cc num_rows_reported $ccnumrows
mce_cmd -qx wb cc num_cols_reported $ccnumcols
mce_cmd -qx wb cc data_rate $datarate
mce_cmd -qx wb rca readout_row_index 0
mce_cmd -qx wb rca readout_col_index $col
#sleep 1
mce_run $filename $sampint $rc
#sleep 1
mce_cmd -qx dsp_reset