#!/bin/bash
# AO -runs mce_fast_acq n times
#
#
#
# loop_acq

source $MAS_SCRIPT/mas_library.bash

mce_cmd -qx wb rca data_mode 1 1
mce_cmd -qx wb rca en_fb_jump 0 0


# for (( tbias=3200; tbias>=1800; tbias=tbias-200 ))
# do
n=0

    while [  $n -le 32 ]; do

   echo "n= $n"

    mce_cmd -qx wb rca readout_row_index $n $n
   mce_cmd -qx rb rca readout_row_index

 # bias_tess $tbias

# echo "bias= $tbias"
   sleep 10

# mce_reconfig

sleep 2
echo "acquire 4min of data"
# mce_fast_acq 100000 s 38 33
   fast_15kHz_acq 100000 1 

sleep 2

 #mce_fast_acq 100000 2 1 1
   fast_15kHz_acq 100000 2

 sleep 5

  let n=n+1
  done

# bias_tess 0
#mce_reset_clean
exit 0