#!/bin/bash

source $MAS_SCRIPT/mas_library.bash

# JAB 20090425
# Accumulate N timestreams 65536 samples long in raw 50MHz mode 12,
# calling mce_raw_acq_1col for col specified, after stopping the mux on the row of interest to take the data open loop.
#
# rawacq_ntimestreams_1pix numbertraces directory mce_col mce_row

if [ "$#" -lt "2" ]; then
 echo "------------------"
 echo "usage: rawacq_ntimestreams_1pix numbertraces dir mce_col mce_row"
exit 1
fi

mce_cmd -qx wb cc internal_cmd_mode 0

mce_reconfig
sleep 1
~/python_tools/really_freeze_servo.py -r $4 --o

sleep 1

if (($3 < 8)); then rc=1; else rc=2; fi
rccol=$(($3 -8*($rc-1)))

extn='row'$4'_col'$3

for (( i = 0 ; i < $1 ; i++ ))
do

#echo "acquiring 65536 raw samples, trace $i of $1 on col$3"

mce_raw_acq_1col $rc $rccol 65536 $extn $2

sleep 1
mce_cmd -qx dsp_reset

done

echo "acquisition of $2 traces complete for col$3"
