#!/bin/bash

set_directory
cd $MAS_DATA
mce_reconfig
mce_zero_bias
mce_cmd -x wb ac enbl_mux 0 
rcnum=$1
chnum=$2
if [ "x$chnum" = "x" ] || [ $chnum -lt 0 ] || [ $chnum -gt 7 ]; then
	chnum=0
fi 
echo "channel = $chnum"
if [ "x$rcnum" = "x" ] || [ $rcnum -lt 1 ] || [ $rcnum -gt 4 ]; then
	rcnum=1
fi 
echo "channel = $chnum"
echo "rc = $rcnum"
a=`date +%H%M`
b=`date +%Y%m%d`
mkdir $a
for i in `seq 1 10 `; do mce_raw_acq_1col $rcnum $chnum "" "" $a ""; sleep 1;  done
cd $a
mce_bin2asc.py `ls *raw`
cd ..
scp -r $a gpd@phas.ubc.ca:~scuba2/public_html/sc2mce/system/psu/test_res/switching_noise/testing_data/UBC/$b/new_psu/




