#!/bin/bash

#initialise environment
if [ ! -x ${MAS_VAR:=/usr/mce/bin/mas_var} ]; then
  echo "Cannot find mas_var.  Set MAS_VAR to the full path to the mas_var binary." >&2
  exit 1
else
  eval $(${MAS_VAR} -s)
fi

source $MAS_SCRIPT/mas_library.bash

if [ "$#" -lt "2" ]; then
  echo "Usage: $0 <sn> <n>" 
  echo "        <sn> is the serial number of the sync box"
  echo "        <n> is the sync-box fo ouput number (0 to 7)"
  exit 1
fi

today=`date +%Y%m%d`_`date +%H%M%S`
sn=$1
ch=$2
filename=$1_$2_$today
full_filename="$MAS_DATA""$filename"
echo "Setup Clock card to use Sync input...."
mce_cmd -x mce_reset
mce_cmd -x dsp_reset

mce_cmd -x wb cc select_clk 1
mce_cmd -x wb cc use_sync 2
mce_cmd -x wb cc use_dv 2

echo "Collect 200 frames of data now, filename=$filename ...."
mce_run $filename 200 2

echo "run eat_packets now to check for sync number consistancy...."
eat_packets -n 1488 -f $full_filename

echo "______________________________________________________________"
echo "Here is the Sync Number of the first 5 data frames, check against fn setting of Sync Box that you just made, it won't be exact, but somewhat close"
for i in `seq 1 5`; do ascii_frame 41 8 $MAS_DATA/$filename $i| head -n1 |awk '{print $11}';done


